name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore --ignore-failed-sources
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore
    - name: Pack
      run: dotnet pack --configuration Release --no-restore
    - name: Publish
      env:
        API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push Dummy/bin/Release/Dummy.1.0.0.nupkg --source github --api-key $env:API_KEY
